### ISSUE TITLE
emoji's won't wrap at the end of a line unless there is extra text after the line

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#100]
This is in Chrome on a Mac in PTT 2.2.1

I've defined a PTT width that should wrap at the dotted blue line

<img width="713" alt="Screen Shot 2021-07-01 at 2 37 08 PM" src="https://user-images.githubusercontent.com/170009/124180597-0930f200-da7a-11eb-97fc-dd20a55755b0.png">

As you can see it doesn't. My text there is "Love all, trust a few, do wrong to none. 😇🇨🇽🎅🏻". However, if I append text to the end of the string like this: "Love all, trust a few, do wrong to none. 😇🇨🇽🎅🏻 this"

<img width="717" alt="Screen Shot 2021-07-01 at 2 37 19 PM" src="https://user-images.githubusercontent.com/170009/124180808-57de8c00-da7a-11eb-8580-19c93c79999a.png">

Then the text wraps properly at the emoji.

**Comment by mimshwright** [comment]
I'll try to reproduce this. but if it's easy for you to check, can you see whether 
1. adding just a space or newline after the emojis makes it wrap?
2. If this happens to other text besides emojis?

**Comment by rizen** [comment]
Sorry for the delay. Adding a space after the emoji is actually worse as the emoji disappears.

**Comment by rizen** [comment]
And yes, it appears if I add just 1 word where there is supposed to be a wrap it doesn't wrap. Likewise if I add a space after that word it causes the word to disappear.

So ultimately I guess this isn't about emoji's but something to do with the wrapping code.

**Comment by apgiorgio** [comment]
I'm also experiencing this issue! When wordWrap is set to true, if the last line should have exactly 1 word, it instead is included in the previous line.

**Comment by mimshwright** [comment]
I'm working on this and #118 at the same time. Both are attempts to fix the wrapping behavior of the last word in a line when it's close to the wrap width.

**Comment by mimshwright** [comment]
To simplify the problem, when the _last_ word in the text pushes the width of the line its on > than the word wrap width, the word **should wrap** to the next line but currently does NOT wrap (it just keeps going)

**Comment by mimshwright** [comment]
Can you guys check out  v2.2.7? This should be working correctly in that version. Let me know if there are still issues.

**Comment by apgiorgio** [comment]
That issue appears to be fixed, but I'm now seeing some issues where an extra space is being added at the beginning of certain lines.  It looks like it's happening in cases where the previous line is especially long, possibly just when the previous line is exactly at the wordWrapWidth.

**Comment by mimshwright** [comment]
If you could give me some testable code for your text field that would be
great

**Comment by mimshwright** [comment]
Also @apgiorgio i don't know if it was a randomly generated one but your avatar looks like a pink skull with sunglasses which is awesome!

**Comment by apgiorgio** [comment]
Okay I managed to recreate it in a reproducible way!
```
const multiStyles = {
                "default": {
                    fontFamily: 'arial',
                    fontSize: 12,
                    fontWeight: 'bold',
                    fill: 0x333333,
                    align: 'left',
                    wordWrap: true,
                    wordWrapWidth: 200
                },
                "kw": {
                    fontFamily: 'arial',
                    fontSize: 12,
                    fill: 0xE24747,
                    fontWeight: 'bold',
                    align: 'left'
                }
            };

let description = new TaggedText("When played, give an allied troop <kw>Summoned</kw>, then sacrifice it.", multiStyles);
```

For me, this ends up displaying the following: 
![image](https://user-images.githubusercontent.com/26915088/126914430-d7243f51-78d9-4ba2-84c8-1c12bea94ddd.png)

**Comment by mimshwright** [comment]
@apgiorgio 2.2.8 should fix it!
Redid/simplified the whole layout sequence.

**Comment by apgiorgio** [comment]
Yeah that looks great, thanks!
