### ISSUE TITLE
Doesn't support % text sizes

### ISSUE THREAD

**Issue by mimshwright** [mimshwright/pixi-tagged-text#107]
According to the pixi documentations, % based strings should be allowed as text sizes (with 100% = 16px) but it actually throws an error. This actually happens with plain PIXI.Text objects but since Pixi-Tagged-Text is built on that component, this component is also broken. 

> TextMetrics.ts:665 Uncaught DOMException: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D': The source width is 0.
>     at Function.TextMetrics.measureFont (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.3.9/pixi.js:32462:34)
>     at Function.TextMetrics.measureText (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.3.9/pixi.js:32075:43)
>     at Text.updateText (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.3.9/pixi.js:32777:37)

**Comment by mimshwright** [comment]
I'll need to search for / make a bug report to the pixi team but will do later.

**Comment by rizen** [comment]
I would absolutely love to see this if you could make it happen, and I'd pay for the dev work on it

**Comment by mimshwright** [comment]
OK. I looked into how this is handled in the code. 

1. The value for `fontSize` ([src](https://github.com/pixijs/pixijs/blob/dev/packages/text/src/TextStyle.ts#L705))
  - if a number, has "px" added to it
  - if a string is unchanged
2.  It's passed directly to `context.font` ([src](https://github.com/pixijs/pixijs/blob/0f150cb709d35dc0c62ae3b48e1c1ecfb70bbbfc/packages/text-bitmap/src/utils/drawGlyph.ts#L40))

So theoretically, any size values supported by [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font) should already work. 

(I'm leaving this here mostly as a note to myself for later)

**Comment by rizen** [comment]
Sorry I meant to reply to this yesterday. Yeah, my thought was #3. Nothing else is really interesting. I realize it's quite a bit of work, but do you have a guess?

**Comment by mimshwright** [comment]
I would say between 1 and 3 hours most likely

**Comment by rizen** [comment]
Oh, no big deal. Let's get it done

**Comment by mimshwright** [comment]
Little hiccup: for some reason the default size for `PIXI.Text` is 26px. I think we should just use 100% == 26px to avoid confusion.

**Comment by rizen** [comment]
Not a problem.  I define a size on my default style anyway.

**Comment by mimshwright** [comment]
@rizen what units are you using for your app besides pixels and %?

**Comment by rizen** [comment]
I only allow pixels to be added through the APP. I have a little conversion utility that will tell people how many pixels are in an inch or whatever. 

My thought was that % would be useful in tag attributes.  I should have probably said that before. I'm sorry I didn't.  I may also, at some point in the future, allow a toggle switch between pixels and percent in the style editor, but that's not the immediate goal as this would be a power user feature.

**Comment by mimshwright** [comment]
Added in v3.4.0
