### ISSUE TITLE
Allow users to override the font-properties of a font

### ISSUE THREAD

**Issue by mimshwright** [mimshwright/pixi-tagged-text#108]
After testing a particularly screwy font (Bebas Neue) we found that we may need a way for users to override the font-properties generated by Pixi so that we can manually tweak the layout. 

Font properties include:
`ascent` - the space above the baseline
`descent` - the space below the baseline
`fontSize` - the sum of the ascent and descent.

**Comment by mimshwright** [comment]
I'm trying to think through how best to do this. Setting it in the style sheet object seems obvious at first, but the font-properties are really a product of the font-family and the font-size so it might require a lot of repeating oneself for different font-sizes or instances of the font. Setting it in options based on the font-family would be the other choice but the font-size is not known to the options object.

A combination would be to set the ascent and descent as percentages of the font-size. So to get a 40px font to have an ascent of 25px and a descent of 15px, you would set the value to `{ascent: 0.625, descent: 0.375 }`. `fontSize` wouldn't need to be included. Come to think of it, you would only really need `ascent` since `descent` would be `1.0 - ascent`. 

So maybe what we need is something in the options object that maps font-family to an ascender-to-descender (baseline) ratio...
// options
{
  baselineRatio: { "Bebas Neue" : 0.625 }
}

That is probably the most  technically correct way to do it but I don't know if that's super logical from a user perspective?

**Comment by rizen** [comment]
So the way I handled it in the past (which probably won't work for PTT) was that all my text had a box model, which allowed me to add spacing on top and bottom to give the place for the letters to render.  

None of what you have laid out here is going to be terribly understandable to a user. But then again, I don't really know what would be. I think like your second way much better than the first.

**Comment by rizen** [comment]
whatever you decide, hoping you figure out a way to add it

**Comment by rizen** [comment]
I've opened a ticket with Pixi.js to fix the root cause of this bug. But of course your baseline override feature would be appreciated in case they never get around to fixing it. https://github.com/pixijs/pixijs/issues/8020

**Comment by mimshwright** [comment]
@rizen 
I've implemented this as an additional mapping of fonts to baseline offset in the options object. Basically, if you find "Bebas Neue" is misaligned by 10px, you can add:
`adjustFontBaseline: { "Bebas Neue": 10 }` 
to your options object. So all pieces of text that use that font will be adjusted. 
I tried some other options while I was working, like changing the ascent and descent in the styles object, and none of them seemed to be ideal. 
Since it's been a while since this issue came up, can you take a look when you can and let me know if this is solving the problem you were having in a way that makes sense?

**Comment by mimshwright** [comment]
also, if you look at the demo html file, you will find a commented out demo of this feature near the bottom.

**Comment by rizen** [comment]
Is there any way we can attach this to the style rather than as an option?

**Comment by mimshwright** [comment]
@rizen Let me see what I can do. I'm a little rusty on why I chose to do it this way.

**Comment by mimshwright** [comment]
@rizen If I can just add vertical padding to the bounding box of each word, would that do it for you?

**Comment by rizen** [comment]
That's what I've already built into my app using https://pixijs.download/dev/docs/PIXI.TextStyle.html#padding

How would what you are saying be different?

**Comment by mimshwright** [comment]
Oh, I didn't realize you've already built that. In fact, I didn't realize there was already a padding property in Pixi if I'm being honest. 

Would it make more sense to just add `adjustFontBaseline` as a style property then?

**Comment by rizen** [comment]
if we can adjust the position of the baseline it will help people who are using 2 different fonts get them to line up correctly, and then they can use the padding to solve the boundary issues.

**Comment by mimshwright** [comment]
I'll add `adjustFontBaseline` to the styles and also keep it in the options on a per-font basis. 
They will be independent values so if they are both set, they will be added together.
