### ISSUE TITLE
Opacity / Alpha

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#164]
I'd like to see an alpha parameter added to text and text stroke separately.

**Comment by mimshwright** [comment]
I think `opacity` and `strokeOpacity` will better match CSS keywords

**Comment by rizen** [comment]
Sounds good

**Comment by mimshwright** [comment]
I wanted to let you know that it's possible to do this currently. Just add an extra two hex digits to the color for `fill` or `stroke` for the alpha channel. 
I'm debating whether it is a good idea to try to add additional keywords do do this automatically (it probably is).

**Comment by rizen** [comment]
Interesting,I didn't realize that pixi.js allowed for 4 digit hex codes. Every example I've ever seen has been 3.

**Comment by mimshwright** [comment]
There is some tricky stuff going on with the colors. I was going to just add an alpha channel as hex numbers to the end of the fill and the stroke color. But the Canvas API is ultimately responsible for parsing the value of the color in the fill. It can be hex values like `#FF3366`, string names like `"red"` or even gradients and patterns. So it's tough to modify this without doing a bunch of conversion or working on a very low level. 

It follows these rules: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillStyle

Text objects have an alpha value and so you can change the value of the entire thing but not the fill and the stroke independently. 

So I think the best way to go for your needs is to use a 32-bit (RGB+A) color picker in your UI or use a 24-bit color picker that creates a hex number to which you add an opacity value.

**Comment by rizen** [comment]
I figured it would work like everything else in pixi.js where I provide you with a hex color 0x008800 for example, and an alpha number float 0.5 (for 50%). 

That way its consistent with pixi stuff.  Thoughts about that?

**Comment by mimshwright** [comment]
PTT is built up of individual text fields and sprites so one could set the opacity for any or all of them. But it will change fill and stroke together. To do them separately, you can use the 4 channel hex code. 
If you want, we can add an opacity field for setting the opacity of every child wrapped in a tag, but to get your original request, it would be better to set the alpha as part of the color in your UI.

**Comment by rizen** [comment]
Ok fair enough
