### ISSUE TITLE
Bug: & displays as &amp;

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#172]
If you have some text that contains & such as "this & that* then it will display as "this \&amp; that"

**Comment by mimshwright** [comment]
@rizen I've just done a super simple test of this and i'm not seeing the issue:

```
const htmlEntityText = `This & that.
This &amp; that.`;
```

Results in:
![image](https://user-images.githubusercontent.com/141928/140430762-0cee7e56-e8af-44df-b592-d21e7167bb61.png)

**Comment by mimshwright** [comment]
I suspect there's a really good chance that your application is escaping the text content at some point and converting symbols into HTML Entities, perhaps when persisting the data or in your UI.

**Comment by rizen** [comment]
How embarrassing. I'm so sorry to have wasted your time.

**Comment by mimshwright** [comment]
Not at all. I suspected this was it and almost said something earlier but i
didn't want to risk wasting YOUR time ¯\_(ツ)_/¯
