### ISSUE TITLE
carriageReturnSpacing property

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#174]
I'd like to add a carriageReturnSpacing property. This would subtract from or add to the lineSpacing property wherever a \n appears. And it would default to 0.

**Comment by mimshwright** [comment]
wonder if we should call this `paragraphMargin` or `paragraphSpacing` for clarity. 

Estimated 1hr to add this.

**Comment by rizen** [comment]
I had considered calling it paragraphSpacing, but ultimately decided that it would mean double carriage returns, but this is per carriage return, so that's why I went with the longer name.

Ultimately I don't care what it is called, so if you have a strong preference for one or the other go for it. 

Timing approved.

**Comment by mimshwright** [comment]
Fixed this in v2.5.0
