### ISSUE TITLE
textTransform vs fontVariant

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#175]
I'd like to see small-caps added to textTransform since fontVariant only has a single use currently.

**Comment by mimshwright** [comment]
That's a feature of Pixi.js' text style; it's not controlled / modified by this library. I've noticed that the convention they have used is to match [CSS' syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant) whenever possible, hence, `fontVariant` is used for small caps despite being the only use case.

**Comment by rizen** [comment]
Not saying it's not that way for a reason, just saying it doesn't make any sense. For example, if you set textTransform to uppercase then fontVariant no longer matters. And since they're mutually exclusive, seems like the interface should simply be merged.

**Comment by mimshwright** [comment]
i see your point. When you use `uppercase`, then the difference between just `uppercase` and `smallcaps + uppercase` would disappear. However, there are some technical differences that make these separate domains. 

`textTransform` - changes the content of the text. It (virtually) replaces the input value of `"aBcDe"` with `"ABCDE"` or `"abcde"` without affecting the font or the original text value.
`fontVariant` - actually uses a different version of the font. AFAIK, it's possible that the small-caps version of the font could be totally different from the normal version - e.g. using ligatures or keeping line widths consistent. And even still, the uppercase and lowercase are still drawn at different sizes. 

In addition, `small-caps + lowercase` or `capitalize` is a different thing than plain `small-caps`. You might also want to use multiple tags that stack to get certain effects:
`"Volume options: <small>Normal <upper>Loud</upper> <lower>Quiet</lower></small>"`

So I respectfully disagree that they're mutually exclusive.

**Comment by rizen** [comment]
I see. Fair enough.
