### ISSUE TITLE
Not compatible with iOS11 or below due to use of "s" (dotAll) Regex flag

### ISSUE THREAD

**Issue by MattShaile** [mimshwright/pixi-tagged-text#180]
iOS11 and below does not support the "s" (dotAll) flag on RegExp.

This flag is used in 2 places in the library. Simply removing them fixes the issue, however I'm sure they're there for a reason.

![image](https://user-images.githubusercontent.com/8725740/141596228-b40b5fa9-db95-4764-b715-b6b90313b977.png)

I can have a look and try and find an alternative way of using dotAll via some kind of shim, but if we can just delete it without consequence, that could be easier

**Comment by mimshwright** [comment]
@MattShaile If the tests pass, it's probably ok to delete. Let me take a quick look.

**Comment by mimshwright** [comment]
It appears that nothing bad happened when i removed the 's', at least on Chromium / MacOS. I actually think this code is based on PixiMultiStyleText's implementation (i.e. it's pretty old and I didn't write it) so it's hard to say why that flag was there in the first place. I'll push a patch.
