### ISSUE TITLE
pixi.js@6 npm ERR! peer pixi.js@"^5.3.9" from pixi-tagged-text@2.5.0

### ISSUE THREAD

**Issue by panhezeng** [mimshwright/pixi-tagged-text#192]
npm ERR! Found: pixi.js@6.2.1
npm ERR! node_modules/pixi.js
npm ERR!   dev pixi.js@"^6.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer pixi.js@"^5.3.9" from pixi-tagged-text@2.5.0
npm ERR! node_modules/pixi-tagged-text
npm ERR!   dev pixi-tagged-text@"^2.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry

**Comment by mimshwright** [comment]
Currently Pixi 6.0 is still not officially supported. The peer dependency requirement is still for version 5. There's a branch to do it and, just due to how I've been prioritizing my work on this, it hasn't been a priority yet. See issue #77
