### ISSUE TITLE
text getting cut at the end 

### ISSUE THREAD

**Issue by ChristieLukose** [mimshwright/pixi-tagged-text#213]
![image](https://user-images.githubusercontent.com/101198906/157267193-d3564b70-01e8-4994-8e0a-0618091010a1.png)

text getting cut at the end  when the last text is italics and bold

**Comment by mimshwright** [comment]
Unfortunately, this is [an issue with PIXI.Text](https://github.com/pixijs/pixijs/issues/5864) and the fix according to them is to add padding. I'm not thrilled with this solution, but it does seem to work: 
<img width="831" alt="Screen Shot 2022-03-08 at 11 30 00" src="https://user-images.githubusercontent.com/141928/157311211-2286a766-e3b7-4e53-8432-865a11cc070e.png">

**Comment by ChristieLukose** [comment]
thank you for the clarity
