### ISSUE TITLE
no break

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#214]
Would it be possible to have a style property to prevent word breaks? 

Basically my use case would be to create a style tag like <nobreak>

```<nobreak>I want this part all together</nobreak> ```

which would force the whole section to the next line if it can't fit on the current line.

**Comment by mimshwright** [comment]
Yeah. I think this would be possible. It's been a while so I'm not 100% sure why the breakwords thing is only done on the whole text instead of styles, so there could be a good reason for it but I can't think of what it would be :D

**Comment by mimshwright** [comment]
I made a little diagram below. Does this seem right?

I'm not sure what should happen with text that is wrapped in no-break styles that won't fit inside `wordWrapWidth`. 

Given
```js
const text = `Really long normal text that breaks to the next line.
Normal text + <nobreak>Text that doesnt' break.</nobreak>
Longer normal text + <nobreak>Text that doesnt' break (wraps line)</nobreak>
<nobreak>Really long text that doesn't break but is too long for the line?</nobreak>
`;
```

Renders
```
----------------------------------------------
|  Really long normal text that breaks to    |
|  the next line.                            |  
|  Normal text + Text that doesn't break.    |
|  Longer normal text +                      |
|  Text that doesn't break (wraps line)      |
|  Really long text that doesn't break but is too long for the line?
|                                            |
----------------------------------------------
```

**Comment by rizen** [comment]
this is exactly what I was hoping for. and yeah, if it wouldn't fit even if it wrapped then I think it has to go off the end like what you show in the diagram

**Comment by mimshwright** [comment]
Notes on implementation:
- There is already a style called `breakWords` defaulting to false so I guess we would call this `breakLines` defaulting to true. Maybe `ignoreWordWrap` default false would be more clear?
- If both `breakWords` is true and `breakLines` is false, there should be a warning and `breakLines` false should get the priority. 
- Behavior of text that goes outside the bounding box (`wordWrapWidth`) is undefined. Use your best judgement and whatever existing defaults in Pixi.Text to determine how to handle it. 
- It may be possible to treat the unbroken text as a single text field in implementation. But that may not be possible if there are tags nested inside.

**Comment by mimshwright** [comment]
@rizen Any thoughts on how to handle nesting of tags inside the no-break style? I assume your users WILL want to nest tags inside of non-breaking text.

1. I'll see what happens as I try to build this. I imagine some weirdness could arise from having different sizes and vertical alignment and stuff like that. So I think we either try to make it work correctly or say "use at your own risk"
2. if you have a nested style that overrides the no-break style, maybe we throw an error.

**Comment by rizen** [comment]
I think that the outer-most no-break is what matters, because I don't think of this as either on or off. It's more like on or undefined. Everything breaks until you see a no break. So in this example:

```
here <nobr>foo bar <red>blood</red> bar foo</nobr> there
```

Everything but "foo bar" and "there" would be no break.

**Comment by mimshwright** [comment]
Added this in v3.13.0!
