### ISSUE TITLE
Justified text with a ragged bottom 

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#215]
Could we get an extra justified mode with a ragged bottom like this 
![](https://media.discordapp.net/attachments/730136311939203204/952300618842787910/Capture.PNG)

**Comment by mimshwright** [comment]
Yes! 
Tbh, i thought it already worked like that but I checked and no. Only the first word on the line aligns left.

I think it makes sense to say:
`justify` = Justified except for the last line
and
`justify-full` or  something like that = Justified including the last line.

However, that would technically be a breaking change.

**Comment by rizen** [comment]
I'm ok if you are

**Comment by mimshwright** [comment]
Also I wonder if there is only one line of text if making it left aligned is a little confusing. Like if you're typing out your first line of text in an editor and it's not Jusified until the line ends. hmmm. Maybe i can look at how some design tools do it.

**Comment by mimshwright** [comment]
I checked how Figma does it and they keep it left aligned until you reach the end of the line. They also don't even have a fullly justified mode. maybe we don't need it either.

**Comment by rizen** [comment]
Adobe Indesign has a crap ton of them:
<img width="230" alt="Screen Shot 2022-03-13 at 10 32 41 AM" src="https://user-images.githubusercontent.com/170009/158067204-50e614e5-f4d7-4745-ba19-a8f231dbafc9.png">

**Comment by rizen** [comment]
I don't think we need to care about the spine, but the other ones all seem useful if we're going to do this.

**Comment by mimshwright** [comment]
Yeah. The spine doesn't even make sense unless it's on a spread. 

So I guess we call them:
- "justify-left", alias "justify"
- "justify-center"
- "justify-right"
- "justify-all"

**Comment by mimshwright** [comment]
Reopening because I just realized that it probably doesn't handle text that has an explicit line-break in it such as:

```
Lorem ipsum dolor   <-- This should be justify
sit amet.\n         <-- This should be left
adipisicing elit.   <-- This should be left
```

Assuming align is "justify-left"...

**Comment by mimshwright** [comment]
@rizen This fix seemed _too easy_ so please keep an eye out for weirdness and I'll try to fix 👍

**Comment by rizen** [comment]
ok, can't wait to try it out. when will it be released?

**Comment by mimshwright** [comment]
It's already released with the caveat about the newline thing.

**Comment by mimshwright** [comment]
I think it's version 3.5.0

**Comment by mimshwright** [comment]
Patched the issue with the newline characters in 3.5.1
