### ISSUE TITLE
parsing error has wrong message

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#224]
If you do something like

```<red fontSize=="75">text</red>```

You get a mismatched tags error, but in reality its a weird attribute assignment.  You might say that this is just the way it is, and that's ok. Just wanted to bring it to your attention in case you wanted to give a more specific error message.

**Comment by mimshwright** [comment]
So if I understand this right, you are saying that this is not a mismatched tag but rather something else. A syntax error?

**Comment by rizen** [comment]
Yup
