### ISSUE TITLE
When `paragraphSpacing` is applied, text and icons on the first line with `valign` other than `"baseline"` are not positioned correctly.

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#235]
If you have an icon that you've wrapped in a tag that changes the vertical alignment to middle, but you're also using paragraph spacing (example 25px for that), then you get this result:

<img width="314" alt="Screen Shot 2022-04-28 at 7 23 02 PM" src="https://user-images.githubusercontent.com/170009/165867840-4de083f3-04a8-4c7e-b048-03b8fdbcaa88.png">

Whereas if I set paragraph spacing back to 0 then I get this result:
<img width="281" alt="Screen Shot 2022-04-28 at 7 24 25 PM" src="https://user-images.githubusercontent.com/170009/165867936-048922b9-4451-44d8-8b95-74a87ab16353.png">

**Comment by mimshwright** [comment]
Ok so in other words, paragraph spacing isn't applied to icons?

**Comment by rizen** [comment]
Yes. You're better at words than me. =)

**Comment by mimshwright** [comment]
Looks like this only happens on the first line of the text too.

<img width="541" alt="Screen Shot 2022-05-29 at 10 42 20" src="https://user-images.githubusercontent.com/141928/170884116-2f56df8f-f174-433b-8fcf-7d30ae0512ac.png">

**Comment by mimshwright** [comment]
It affects all middle-alignment, not just icons. 
<img width="535" alt="Screen Shot 2022-05-29 at 10 45 34" src="https://user-images.githubusercontent.com/141928/170884248-273ba02b-5500-410b-8c2e-91b090b4238f.png">

**Comment by mimshwright** [comment]
Fixed in v3.7.3 but **please use version v3.7.4 instead!  v3.7.3 may have been corrupted during build.**
