### ISSUE TITLE
Cannot use font with space in the name in fontFamily attribute

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#258]
Get this error: undefined is not an object (evaluating 'n[1].substr')

```<body fontFamily="Arimo Bold">This</body>```

**Comment by rizen** [comment]
That same font works fine if I define a style using it. Also tried it with other fonts with the same result. Works as a style, but not in an attribute.

**Comment by mimshwright** [comment]
Good catch. Should be a quick fix.

**Comment by mimshwright** [comment]
fixed in 3.7.5
