### ISSUE TITLE
PTT stealing extra pixel space at the bottom

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#263]
For some reason the bounding box of a text area gets a larger and larger amount of padding at the bottom based upon the number of lines in it. Not sure why that is. Or why it even has any extra padding at the bottom.

<img width="624" alt="Screen Shot 2022-06-20 at 10 00 29 AM" src="https://user-images.githubusercontent.com/170009/174630403-85375d53-7cfc-437b-8526-7e70339a7190.png">
<img width="640" alt="Screen Shot 2022-06-20 at 9 58 23 AM" src="https://user-images.githubusercontent.com/170009/174630405-ca796111-8706-439a-ba19-61d712621165.png">

**Comment by mimshwright** [comment]
that's a pretty weird one. 

I won't be able to respond to this for a while. Got super busy.

**Comment by mimshwright** [comment]
I'm not really even sure what mechanism is creating the bounding box. I guess it's the Sprite in TaggedText or one of the other containers within? AFAIK I don't remember ever setting the height of the bounding box explicitly.

**Comment by rizen** [comment]
I have discovered that this isn't PTT, it's the wrapper I'm putting around PTT.
