### ISSUE TITLE
inline icon sizing

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#329]
Inline icons are often too small relative to text when they get inlined. I usually end up doing something like:

```
This is my <icon><gun/></icon> in my text.
```
And then set a percentage increase on the icon style. However, this gets verbose. It would be cool if we could do one or more of the following (in order of my preference, but do whichever is easy to implement):

- Set a percentage increase on inline icons as a type somehow. If I could set something in the default styles that would only target inline icons while leaving text alone.
- Set a percentage increase for inline icons on the PTT object
- Set a percentage increase on each icon relative to its text. Like 100 would be the size of the text, where 150 would be 50% larger than the text it is inlined with.

**Comment by mimshwright** [comment]
I wrote the below text and then realized the icons you're probably referring to are the inline images. So you can disregard this, but still good to know. 

---
There is currently a way to do this. Every emoji is wrapped automatically with an `<__EMOJI__>` tag. You can use that tag to change the relative size of all the emojis in the component. 

e.g. 
```css
{
  __EMOJI__: {
    textSize: "120%"
  }
}
```

I tested it and found a bug where the styles weren't being applied but i fixed that in v3.10.1

**Comment by mimshwright** [comment]
Currently, the icons are scaled to 80% of the text size by default. This is basically hard coded and probably the best way to do this is to move that hard-coded value into the style object. So you'd be able to set `iconScaling` (or whatev) on the default style or any other tags.

**Comment by rizen** [comment]
Sounds good.

**Comment by mimshwright** [comment]
Added `iconScale` as a new style in 3.11.0
