### ISSUE TITLE
Inline style string properties are truncated if they contain "="

### ISSUE THREAD

**Issue by Slynchy** [mimshwright/pixi-tagged-text#338]
### Expected Behavior
A text tag with an inline string property that contains an equals sign ("=") should return the full string when later queried via `textInstance.style.propertyName`

### Current Behavior
A text tag with an inline string property that contains an equals sign ("=") has its text truncated when later queried via `textInstance.style.propertyName`

Example: `<hyperlink url="someBase64=">Text</hyperlink>` will create a Text object where `style.url == "someBase6"`

### Steps to Reproduce
```
        import TaggedText from "pixi-tagged-text";
        function testPIXITaggedTextBug() {
            const taggedText = new TaggedText(
                "<test propertyTest='this will get truncated='>Test</test>",
                {
                    "test": {
                        fontFamily: "Times New Roman",
                        fontSize: 11,
                        align: "left",
                        fontWeight: "bold",
                    }
                }
            );
            taggedText.update();
            taggedText.textFields.forEach((e) => {
                // @ts-ignore
                const prop: string = e.style?.propertyTest;
                if(prop) {
                    e.on("pointerup", () => {
                        // @ts-ignore
                        const url = e.style?.propertyTest;
                        if(url) {
                            console.error(url);
                            // output: `this will get truncate`
                        }
                    });
                    e.emit("pointerup");
                }
            });
        }
```

### Environment

- **`pixi-tagged-text` version**: 3.11.0
- **`node` version**: v18.14.0
- **`npm` version**: 9.3.1
- **`pixi.js` version**: 6.3.2
- **Browser & Version**: 110.0.5481.178
- **OS & Version**: Windows 11

**Comment by mimshwright** [comment]
Hey @Slynchy . I expect this is some sloppy RegEx code. I don't know if/when I'll be able to fix it but if you'd like to write a test and do a PR, I'll try to get it reviewed and merged asap.
