### ISSUE TITLE
`splitStyle="characters"` doesn't wrap when a word reaches the `wordWrap` limit

### ISSUE THREAD

**Issue by mimshwright** [mimshwright/pixi-tagged-text#48]
Repro:
Create a TaggedText with the `splitStyle` option set to `"characters"`. 
Make sure that `wordWrap` is `true` and the `wordWrapWidth` is short while the text is long.
Expected:
Text should break in the middle of a word and wrap to the next line.
Actual:
Text never breaks. it just keeps going off the edge.
<img width="588" alt="Screen Shot 2021-05-16 at 15 36 35" src="https://user-images.githubusercontent.com/141928/118414994-9ea82c00-b65c-11eb-8a08-c1a1535315f0.png">

**Comment by mimshwright** [comment]
Make a note in docs that this was called "breakWords" in previous versions.

**Comment by zhongying1995** [comment]
hi
can u fix the bug?
when i use chinese,They never wrap new lines

**Comment by mimshwright** [comment]
@zhongying1995 I haven't been able to totally fix this but maybe it'll be improved now in 3.14.0. See if it'll work for you.
You must use the style `breakWords: true` and also the option property `splitStyle: "characters"` otherwise it can lead to issues with the layout of the text. I'll open a new bug for this to try to make it work property without requiring `splitStyle`
