### ISSUE TITLE
Support for underline, overline, and strikethrough

### ISSUE THREAD

**Issue by mimshwright** [mimshwright/pixi-tagged-text#68]
Should support following style properties:
- `textStyle = underline` - Adds an underline of default thickness.
- `underlineThickness` - Optional thickness of line. Like strokeThickness, doesn't appear if zero.
- `underlineColor` - Default value is the fill color
- `underlineOffset` - Optional parameter to tweak the spacing of the underline from the baseline.

If `textDecoration` is set to `"underline"`, an underline will be added with default thickness, color and offset. A text without `textDecoration="underline"` can still have an underline by directly setting thickness and color. Thickness will be relative to font-size, not less than 0. Offset default should be halfway between the baseline and descender line but possibly also influenced by thickness.

Overline and strikethrough will also be supported with similar properties. Strikethru should appear halfway between the top of the ascender and the baseline, overline should appear half the descender height above the ascender.

**Comment by mimshwright** [comment]
@rizen How's this look?

**Comment by rizen** [comment]
looks perfect!

**Comment by mimshwright** [comment]
Slightly changing this to more closely match the CSS properties for underlines. 
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration

**Comment by mimshwright** [comment]
Added in v2.1.1
