### ISSUE TITLE
letter scaling

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#87]
I'm not sure this is possible (or easy), but I thought of another feature I used to have that might be nice in PTT. You could stretch or shrink the text in x and y separately. Not the spacing of the text, but the individual letters.
<img width="435" alt="Screen Shot 2021-06-15 at 2 28 23 PM" src="https://user-images.githubusercontent.com/170009/122111971-f4036480-cde5-11eb-8b8a-711368368f25.png">

**Comment by mimshwright** [comment]
Yes. i think this is pretty doable. We could add properties for
- `scaleX`
- `scaleY`
Each segment of text which is created would be scaled first before being positioned.

**Comment by rizen** [comment]
Ok, let's do it

**Comment by mimshwright** [comment]
I started this and realized that things get a little complicated with vertical layout and baselines when you can scale the height. What do you think about only having `scaleWidth` and using fontSize to scale the height?

**Comment by rizen** [comment]
Font size is not the same as scaling height, because font size also scales the width at the same time. If you're telling me it's too complicated to do scale height, then ok, but don't present scaling font as if its the same thing. =)

If its complicated, but doable, tell me what its going to cost me and I can make a decision.

**Comment by rizen** [comment]
For the record, I understand that you can set the font to the height you need and then scale the width to get the narrower but taller variant. But that's not quite as intuitive to the user. Hence why I said its not the same thing.

**Comment by mimshwright** [comment]
OK. I understand.
- I was concerned about the complications in adjusting the font metrics (like positioning the baseline, etc.) but I think I can work around it. I could for example make `scaleY` be a syntactic sugar for setting `fontSize * scaleY` & `scaleX / scaleY` internally so we should get the same result but with a nicer interface.
- Alternative would be to do this in your UI, but I agree that keeping a scaleY is more intuitive.

BTW, I'm about finished with the width now, just need to update the rendering function.

**Comment by mimshwright** [comment]
Published in v2.2.0
Final names for the properties are:
`fontScaleWidth`
`fontScaleHeight`
Both only accept decimal numbers and default to 1.0

**Comment by mimshwright** [comment]
tweak in 2.2.1
Now values that are NaN or < 0 are converted to 0.

**Comment by rizen** [comment]
This works exactly as expected except for one thing. As you scale the text up it becomes blurry.  

<img width="602" alt="Screen Shot 2021-07-01 at 3 28 22 PM" src="https://user-images.githubusercontent.com/170009/124185779-07b6f800-da81-11eb-9efd-5a19a371c82f.png">

This tells me that you're capturing the text at the defined font size and then scaling up. Would it be possible to always capture it at the largest size and then scale down to fit the demands of scaling? 

For example, if the font is set at 50px, but then you're told to scale 2.0, then set the font size to 100px, and scale the other direction back to what it was originally.

**Comment by rizen** [comment]
here's the fiddle for my experiment: https://jsfiddle.net/plainblackguy/xkL0g2j3/5/
