### ISSUE TITLE
textDecorations (underlines) don't appear under spaces by default

### ISSUE THREAD

**Issue by mimshwright** [mimshwright/pixi-tagged-text#97]
This is a quasi-bug / need for improvement. 

When you create text, with text decorations (aka, underline, overline, line-through) by default, it renders in such a way that the underlines won't appear for any whitespace. This is because each underline is paired with a text segment* and by default, we do not actually draw the whitespace characters when rendering the text. 

> <img width="563" alt="drawWhitespace off" src="https://user-images.githubusercontent.com/141928/123450978-1d648300-d592-11eb-8784-7de28ed9f36a.png">

> _`options.drawWhitespace = false` (default)_

There is an option to force the whitespace to be drawn, `drawWhitespace`, and when set to true, the results look as expected.
> <img width="559" alt="drawWhitespace on" src="https://user-images.githubusercontent.com/141928/123451057-353c0700-d592-11eb-873a-4cf9dcf25081.png">

> `options.drawWhitespace = true`

As a temporary fix, I've added a warning to the console when you try to use underlines but have `drawWhitespace` set to `false`.
> <img width="664" alt="warning" src="https://user-images.githubusercontent.com/141928/123451379-70d6d100-d592-11eb-9bb0-f3c395af96b7.png">

> _Console warning_

A better solution would be to draw a single underline per line of text for the entire set of text segments in a tag. This would require refactoring the `draw()` method in TaggedText to create only one underline per tag per line. 

*: Usually a _segment_ is a single word but for words that have multiple tags, or a tag in the middle of the word, or when `splitStyle="characters"`, a segment might be a portion of a word or a single character.

**Comment by mimshwright** [comment]
@rizen I decided to go ahead with releasing underlines despite this. But let me know if you think it's worth refactoring to fix.

**Comment by rizen** [comment]
What happens when drawWhitespace is set to true, but there is no underline, strikethru, or overline?

**Comment by mimshwright** [comment]
It draws the whitespace but you just don't see it because it's whitespace :D

**Comment by rizen** [comment]
I'll probably just set drawWhitespace to true in my app then if there's no huge performance penalty. So I guess my answer is I don't need the refactoring.

**Comment by mimshwright** [comment]
Closing since this is a very low priority and a fairly high level of effort. Future users, feel free to reopen if it's an issue for you!
